eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    service0: /service0/**
    service1: /service1/**

##更新ereka负载